title: "Manuel Silva Vega"
description: "GeoAI & Remote Sensing for Mine Waste Stability in Chile"
theme: jekyll-theme-minimal

logo: /assets/silva.jpg

github_username: msilvav
linkedin: "https://www.linkedin.com/in/msilvavega/"

header_pages:
  - research.md
  - teaching.md
  - datasets.md
  - awards.md
  - publications.md
